In [146]:
# load packages
import numpy as np
import pandas as pd
import ast

In [147]:
# load datasets
movies = pd.read_csv('movies.csv')
credits = pd.read_csv('credits.csv')
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [148]:
# Merge and filter dataset for desired columns
movies_df = movies.merge(credits, on= 'title')
movies_df = movies_df[['movie_id', 'title', 'overview', 'genres', 'keywords', 'cast', 'crew']]
display(movies_df.head())

movie_id                                     title  \
0     19995                                    Avatar   
1       285  Pirates of the Caribbean: At World's End   
2    206647                                   Spectre   
3     49026                     The Dark Knight Rises   
4     49529                               John Carter   

                                            overview  \
0  In the 22nd century, a paraplegic Marine is di...   
1  Captain Barbossa, long believed to be dead, ha...   
2  A cryptic message from Bond’s past sends him o...   
3  Following the death of District Attorney Harve...   
4  John Carter is a war-weary, former military ca...   

                                              genres  \
0  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
1  [{"id": 12, "name": "Adventure"}, {"id": 14, "...   
2  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
3  [{"id": 28, "name": "Action"}, {"id": 80, "nam...   
4  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   

                                            keywords  \
0  [{"id": 1463, "name": "culture clash"}, {"id":...   
1  [{"id": 270, "name": "ocean"}, {"id": 726, "na...   
2  [{"id": 470, "name": "spy"}, {"id": 818, "name...   
3  [{"id": 849, "name": "dc comics"}, {"id": 853,...   
4  [{"id": 818, "name": "based on novel"}, {"id":...   

                                                cast  \
0  [{"cast_id": 242, "character": "Jake Sully", "...   
1  [{"cast_id": 4, "character": "Captain Jack Spa...   
2  [{"cast_id": 1, "character": "James Bond", "cr...   
3  [{"cast_id": 2, "character": "Bruce Wayne / Ba...   
4  [{"cast_id": 5, "character": "John Carter", "c...   

                                                crew  
0  [{"credit_id": "52fe48009251416c750aca23", "de...  
1  [{"credit_id": "52fe4232c3a36847f800b579", "de...  
2  [{"credit_id": "54805967c3a36829b5002c41", "de...  
3  [{"credit_id": "52fe4781c3a36847f81398c3", "de...  
4  [{"credit_id": "52fe479ac3a36847f813eaa3", "de...

In [149]:
# Filter missing values
print(movies_df.isnull().sum())
print(movies_df.duplicated().sum())
movies_df.dropna(inplace= True)# drop missing values

movie_id    0
title       0
overview    3
genres      0
keywords    0
cast        0
crew        0
dtype: int64
0


In [150]:
# clean values in dataset
# print(movies_df.iloc[0].crew)

def convert(obj): # pulls out name from the dicts imbeded in the list
    l = []
    for i in ast.literal_eval(obj):
        l.append(i['name'])
    return l

def convert3(obj): # pulls out name from the dicts imbeded in the list for cast
    l = []
    counter = 0
    for i in ast.literal_eval(obj):
        if counter !=3:
            l.append(i['name'])
            counter += 1
        else:
            break
        return l
    
def getDirector(obj): # pulls out name from the dicts imbeded in the list for cast
    l = []
    for i in ast.literal_eval(obj):
        if i['job'] == 'Director':
            l.append(i['name'])
            break
    return l
    

In [151]:
# apply functions to desired columns

# Genre
movies_df['genres'] = movies_df['genres'].apply(convert)
movies_df['genres'] = movies_df['genres'].apply(lambda x:[i.replace(" ","") for i in x])

# keywords
movies_df['keywords'] = movies_df['keywords'].apply(convert)
movies_df['keywords'] = movies_df['keywords'].apply(lambda x:[i.replace(" ","") for i in x])

# Cast
movies_df['cast'] = movies_df['cast'].apply(convert3)
movies_df['cast'] = movies_df['cast'].apply(lambda x: [i.replace(" ", "") for i in x] if x is not None else [])

# Crew/Director
movies_df['crew'] = movies_df['crew'].apply(getDirector)
movies_df['crew'] = movies_df['crew'].apply(lambda x:[i.replace(" ","") for i in x])

# Overview
movies_df['overview'] = movies_df['overview'].apply(lambda x:x.split())

# Tags
# combine into a single 'tags' column
movies_df['tags'] = movies_df['overview'] + movies_df['genres'] + movies_df['keywords'] + movies_df['crew']
display(movies_df.head())

movie_id                                     title  \
0     19995                                    Avatar   
1       285  Pirates of the Caribbean: At World's End   
2    206647                                   Spectre   
3     49026                     The Dark Knight Rises   
4     49529                               John Carter   

                                            overview  \
0  [In, the, 22nd, century,, a, paraplegic, Marin...   
1  [Captain, Barbossa,, long, believed, to, be, d...   
2  [A, cryptic, message, from, Bond’s, past, send...   
3  [Following, the, death, of, District, Attorney...   
4  [John, Carter, is, a, war-weary,, former, mili...   

                                         genres  \
0  [Action, Adventure, Fantasy, ScienceFiction]   
1                  [Adventure, Fantasy, Action]   
2                    [Action, Adventure, Crime]   
3              [Action, Crime, Drama, Thriller]   
4           [Action, Adventure, ScienceFiction]   

                                            keywords              cast  \
0  [cultureclash, future, spacewar, spacecolony, ...  [SamWorthington]   
1  [ocean, drugabuse, exoticisland, eastindiatrad...      [JohnnyDepp]   
2  [spy, basedonnovel, secretagent, sequel, mi6, ...     [DanielCraig]   
3  [dccomics, crimefighter, terrorist, secretiden...   [ChristianBale]   
4  [basedonnovel, mars, medallion, spacetravel, p...    [TaylorKitsch]   

                 crew                                               tags  
0      [JamesCameron]  [In, the, 22nd, century,, a, paraplegic, Marin...  
1     [GoreVerbinski]  [Captain, Barbossa,, long, believed, to, be, d...  
2         [SamMendes]  [A, cryptic, message, from, Bond’s, past, send...  
3  [ChristopherNolan]  [Following, the, death, of, District, Attorney...  
4     [AndrewStanton]  [John, Carter, is, a, war-weary,, former, mili...

In [152]:
# Create new dataframe
new_df = movies_df[['movie_id', 'title', 'tags']]

# Clean new dataframe
new_df['tags'] = new_df['tags'].apply(lambda x: ' '.join(x))
new_df['tags'] = new_df['tags'].apply(lambda x:x.lower())
display(new_df.head())

/var/folders/xn/5hn8zsqn2j1d2ghwqqkc02vnpmp2n3/T/ipykernel_90453/3837544231.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x: ' '.join(x))
/var/folders/xn/5hn8zsqn2j1d2ghwqqkc02vnpmp2n3/T/ipykernel_90453/3837544231.py:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x:x.lower())


movie_id                                     title  \
0     19995                                    Avatar   
1       285  Pirates of the Caribbean: At World's End   
2    206647                                   Spectre   
3     49026                     The Dark Knight Rises   
4     49529                               John Carter   

                                                tags  
0  in the 22nd century, a paraplegic marine is di...  
1  captain barbossa, long believed to be dead, ha...  
2  a cryptic message from bond’s past sends him o...  
3  following the death of district attorney harve...  
4  john carter is a war-weary, former military ca...

In [153]:
# Importing CountVectorizer from the scikit-learn library for feature extraction
from sklearn.feature_extraction.text import CountVectorizer

# Instantiate the CountVectorizer with a maximum of 5000 features and excluding common English stop words
cv = CountVectorizer(max_features=5000, stop_words='english')

# Fit the CountVectorizer to the 'tags' column in the new_df DataFrame and transform it into a term-document matrix
# This converts text data into a matrix of token counts (features), where each row corresponds to a document (entry)
print(cv.fit_transform(new_df['tags']).toarray().shape)  # Print the shape of the resulting matrix to check dimensions

# Store the transformed text data (term-document matrix) in the 'vectors' variable
vectors = cv.fit_transform(new_df['tags']).toarray()

# Print the first row of the transformed matrix to see the token counts for the first document
print(vectors[0])

# Print the total number of unique features (words) considered after the vectorization process
print(len(cv.get_feature_names_out()))


(4805, 5000)
[0 0 0 ... 0 0 0]
5000


In [154]:
# Importing the Natural Language Toolkit (nltk) library
import nltk
from nltk.stem.porter import PorterStemmer

# Creating an instance of the PorterStemmer
ps = PorterStemmer()

# Function to apply stemmer
def stem(text):
    y = [] 
    # Splitting the input text into individual words and iterating over them
    for i in text.split():
        y.append(ps.stem(i))
    return " ".join(y)  # Joining the stemmed words back into a single string with spaces in between

new_df['tags'] = new_df['tags'].apply(stem)


/var/folders/xn/5hn8zsqn2j1d2ghwqqkc02vnpmp2n3/T/ipykernel_90453/4073192622.py:16: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(stem)


In [155]:
# Importing the cosine_similarity function from the sklearn.metrics.pairwise module
from sklearn.metrics.pairwise import cosine_similarity

# Calculating the cosine similarity between all pairs of vectors
# This returns a similarity matrix where each element (i, j) represents the cosine similarity between vectors i and j
similarity_matrix = cosine_similarity(vectors)

print(f"Cosine Similarity Matrix:\n{similarity_matrix}\n")

# Printing the shape of the similarity matrix to verify its dimensions
# The shape should be (number of documents, number of documents)
print(f"Shape of Cosine Similarity Matrix: {similarity_matrix.shape}\n")

# Store the matrix for easier use
similarity = cosine_similarity(vectors)

# Printing the cosine similarity values for the first document against all other documents
print(f"Cosine Similarity for the first document against all documents:\n{similarity[0]}\n")

# Printing the shape of the similarity vector for the first document
# The shape should be (number of documents,)
print(f"Shape of Cosine Similarity vector for the first document: {similarity[0].shape}\n")

# Sorting and printing the indices of the top 5 most similar documents to the first document, excluding the first one itself
# Enumerate creates pairs of (index, similarity value), sorted by similarity value in descending order
# The [1:6] slice excludes the first entry, which is the document itself with a similarity of 1
top_similarities = sorted(list(enumerate(similarity[0])), reverse=True, key=lambda x: x[1])[1:6]
print(f"Top 5 most similar documents to the first document: {top_similarities}")


Cosine Similarity Matrix:
[[1.         0.09284767 0.06085806 ... 0.02431083 0.02668803 0.        ]
 [0.09284767 1.         0.06780635 ... 0.02708645 0.         0.        ]
 [0.06085806 0.06780635 1.         ... 0.02663118 0.         0.        ]
 ...
 [0.02431083 0.02708645 0.02663118 ... 1.         0.07007128 0.04732485]
 [0.02668803 0.         0.         ... 0.07007128 1.         0.05195243]
 [0.         0.         0.         ... 0.04732485 0.05195243 1.        ]]

Shape of Cosine Similarity Matrix: (4805, 4805)

Cosine Similarity for the first document against all documents:
[1.         0.09284767 0.06085806 ... 0.02431083 0.02668803 0.        ]

Shape of Cosine Similarity vector for the first document: (4805,)

Top 5 most similar documents to the first document: [(539, 0.26940795304016235), (1194, 0.2545875386086578), (507, 0.2518277005725965), (1216, 0.24459979523511427), (260, 0.2434322477800738)]


In [156]:
# Movie Recommendation Function
def recomend(movie):
    # Find the index of the movie in the DataFrame
    movie_index = new_df[new_df['title'] == movie].index[0]
    
    # Retrieve the similarity scores for the movie
    distances = similarity[movie_index]
    
    # Create a list of movie indices and their similarity scores, sorted by similarity in descending order
    # The [1:6] slice skips the first movie (itself) and gets the top 5 similar movies
    movies_list = sorted(list(enumerate(distances)), reverse=True, key=lambda x: x[1])[1:6]

    # Print the titles of the top 5 recommended movies
    for i in movies_list:
        print(f"Recommended Movie: {new_df.iloc[i[0]].title}")

# Example usage
# recomend("The Matrix")  # Replace "The Matrix" with any movie title from your DataFrame to get recommendations


In [157]:
recomend('The Matrix')

Recommended Movie: The Matrix Revolutions
Recommended Movie: The Matrix Reloaded
Recommended Movie: Æon Flux
Recommended Movie: Jupiter Ascending
Recommended Movie: Hackers


In [158]:
recomend('Iron Man')

Recommended Movie: Iron Man 2
Recommended Movie: Iron Man 3
Recommended Movie: Avengers: Age of Ultron
Recommended Movie: Ant-Man
Recommended Movie: X-Men


In [159]:
recomend('Captain America: Civil War')

Recommended Movie: Captain America: The First Avenger
Recommended Movie: Captain America: The Winter Soldier
Recommended Movie: Avengers: Age of Ultron
Recommended Movie: Iron Man 3
Recommended Movie: Ant-Man
